# Generated by Django 5.1.1 on 2024-09-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='localtion',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='localtion',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
